name: Sync from TEST
on:
  workflow_dispatch: {}
permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PROD
        uses: actions/checkout@v4

      - name: Checkout TEST
        uses: actions/checkout@v4
        with:
          repository: BlackStar1523/CakeTest.github.io
          token: ${{ secrets.SYNC_TEST }}   # ou PUSH_TEST si c'est ton nom
          path: test-src

      - name: Dry-run diff
        run: |
          rsync -a --delete --dry-run \
            --exclude ".git" \
            --exclude ".github/workflows" \
            --exclude "assets/JS/config.js" \
            test-src/ ./

      - name: Sync files (copy)
        run: |
          rsync -a --delete \
            --exclude ".git" \
            --exclude ".github/workflows" \
            --exclude "assets/JS/config.js" \
            test-src/ ./ || code=$?
          if [ "${code:-0}" = "24" ]; then
            echo "rsync reported vanished files (code 24) — continuing"
          elif [ "${code:-0}" != "0" ]; then
            exit $code
          fi

      - name: Commit & push
        run: |
          git status
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add -A
            git commit -m "Sync from TEST (auto)"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
