name: Sync from TEST

on:
  workflow_dispatch: {}        # lancement manuel
  schedule:
    - cron: "0 6 * * *"        # optionnel: 06:00 UTC chaque jour

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout PROD (repo courant)
      #    ⚠️ on NE met PAS persist-credentials:false pour garder GITHUB_TOKEN
      - name: Checkout PROD
        uses: actions/checkout@v4

      # 2) Checkout TEST avec ton PAT (lecture)
      - name: Checkout TEST
        uses: actions/checkout@v4
        with:
          repository: BlackStar1523/CakeTest.github.io
          token: ${{ secrets.PUSH_TEST }}
          path: test-src

      # 3) Diff rapide pour log
      - name: Show diff (what will change)
        run: |
          rsync -a --delete --dry-run \
            --exclude ".git" \
            --exclude ".github/workflows" \
            --exclude "assets/JS/config.js" \
            test-src/ ./

      # 4) Sync fichiers de TEST -> PROD (en excluant ce qu'on veut garder)
      - name: Sync files (copy)
        run: |
          rsync -a --delete \
            --exclude ".git" \
            --exclude ".github/workflows" \
            --exclude "assets/JS/config.js" \
            test-src/ ./

      # 5) Commit & push si changements
      - name: Commit & push
        run: |
          git status
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add -A
            git commit -m "Sync from TEST (auto)"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
